expose transit state details
rarimo/rarime pull request #10
Opened 2023-10-17 17:24 UTC by lukachi

2023-10-17 21:30 UTC, ihordiachenko commented
@lukachi  Update the changelog

2023-10-17 21:37 UTC, ihordiachenko requested changes

2023-10-17 21:37 UTC, ihordiachenko commented on packages/connector/src/types.ts
> +    root: string | number;
Are you sure it's not just a `string`?

2023-10-18 09:41 UTC, lukachi commented on packages/connector/src/types.ts
> +    root: string | number;
it's Bignumberish, but i wont add ethers js package into project, so `string | number` would be pretty enough

2023-10-19 12:21 UTC, ihordiachenko approved these changes

2023-10-19 12:21 UTC, ihordiachenko commented on CHANGELOG.md
> +### Added
```suggestion
### Changed
```

2023-10-19 12:21 UTC, ihordiachenko commented on CHANGELOG.md
> +- `@rarimo/rarime`: expose transit state details on `createProof`, update `IssuerData` and `BJJSignatureProof2021` classes
>update `IssuerData` and `BJJSignatureProof2021` classes

Add some context why did you update them and how

2023-10-19 12:39 UTC, ihordiachenko commented on CHANGELOG.md
> +  - rearrange loading state details, cause generating proof must be specific by block to prevent possible conflicts
```suggestion
  - use the state at a specific block when generating the proofs to prevent possible conflicts
```

2023-10-19 12:52 UTC, ihordiachenko commented on CHANGELOG.md
> +## [0.6.0] - 2023-10-18
```suggestion
## [0.6.0] - 2023-10-19
```

2023-10-19 12:54 UTC, merged