Feature/import key
rarimo/rarime pull request #37
Opened 2024-02-05 12:05 UTC by lukachi

2024-02-06 14:12 UTC, ardier16 commented on packages/snap/src/index.ts
> +        const identity = await Identity.create(params?.privateKeyHex);
does it use `snap_getEntropy` when private key is not passed?

2024-02-06 14:12 UTC, ardier16 commented on packages/snap/src/helpers/credential-helpers.ts
> +  const entropyIdentity = await Identity.create(entropyKeyHex);
isn't `entropyKeyHex === entropyIdentity.privateKeyHex`?

2024-02-06 15:36 UTC, ihordiachenko commented
Add changelog

2024-02-06 15:37 UTC, ihordiachenko requested changes

2024-02-06 15:37 UTC, ihordiachenko commented on packages/connector/src/types.ts
> +export type CreateIdentityRequestParams = {
Add documents for the new RPC method params

2024-02-06 15:47 UTC, ihordiachenko commented
@lukachi let's add a domain whitelist check too for now

2024-02-09 17:01 UTC, ardier16 commented on CHANGELOG.md
> +  - `getIdentity` rpc method
```suggestion
  - `GetIdentity` RPC method
```

2024-02-09 17:01 UTC, ardier16 commented on CHANGELOG.md
also `CreateIdentity` method is changed

2024-02-09 17:01 UTC, ardier16 commented on packages/connector/README.md
> +### get identity
```suggestion
### Get identity
```

2024-02-09 17:01 UTC, ardier16 commented on packages/connector/README.md
> +### get identity
let's add docs for createIdentity with pkHex

2024-02-09 17:01 UTC, ardier16 commented on packages/snap/README.md
> +Returns did and did in big int string format if they are exists, otherwise method throws error.
DID

2024-02-09 17:01 UTC, ardier16 commented on packages/snap/README.md
> +### Create an identity
Get identity

2024-02-09 17:01 UTC, ardier16 commented on packages/snap/src/index.ts
> +        throw new Error('This origin does not have access to export identity');
remove credentials

2024-02-09 17:01 UTC, ardier16 commented on packages/snap/src/index.ts
> +      const params = (request.params as any) as CreateIdentityRequestParams;
any?

2024-02-09 17:01 UTC, ardier16 commented on packages/snap/src/index.ts
> +      const keyHex = entropy.startsWith('0x') ? entropy.substring(2) : entropy;
not needed if you have privateKey imported

2024-02-12 10:23 UTC, ardier16 approved these changes

2024-02-12 10:23 UTC, ardier16 commented on CHANGELOG.md
>    - `getIdentity` rpc method
`GetIdentity` RPC method

2024-02-12 10:23 UTC, ardier16 commented on CHANGELOG.md
> +  - `CreateIdentity` - now can generate from a private key hex from params
mb?
 ```suggestion
   - `CreateIdentity` - accept `privateKeyHex` optional param for identity creation
```

2024-02-12 10:24 UTC, ardier16 commented on packages/snap/src/index.ts
> +      const params = request.params as CreateIdentityRequestParams;
let's check origin whitelist if `privateKeyHex` param is passed

2024-02-12 10:41 UTC, ihordiachenko commented
@lukachi use more descriptive PR names. E.g.: "Added option for importing the private key" instead of "Import private key"

2024-02-12 10:44 UTC, ihordiachenko commented on packages/connector/README.md
> +Returns DID and DID in big int string format if they are exists, otherwise method throws error.
```suggestion
Returns DID in string and BigInt string formats. Throws error if the DID wasn't initialised yet.
```

2024-02-12 10:46 UTC, ihordiachenko commented on packages/snap/src/helpers/credential-helpers.ts
> +        throw new Error('Identity not created yet');
```suggestion
        throw new Error('Identity was not created yet');
```

2024-02-12 10:48 UTC, ihordiachenko commented on packages/snap/src/index.ts
> +          'This origin does not have access to remove credentials',
```suggestion
          'This origin does not have access to the RemoveCredentials method',
```

2024-02-12 11:54 UTC, merged